name: Daily Script
on:
  schedule:
    - cron: '45 17 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      
      - name: Run script
        env:
          my_email: ${{ secrets.my_email }}
          my_password: ${{ secrets.my_password }}
        run: python sender.py
